//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAssignment.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistribution
    {
        public int ID { get; set; }
        public int CollectRequestID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public string Quantity { get; set; }
        public string RequestType { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
